### ISSUE TITLE
Link to the homepage asks to be opened in external application

### ISSUE THREAD

**Issue by NobbZ** [alexdovzhanyn/amethyst#1]
When I follow the link to the homepage from the repositories main page, then my browser asks me to open the link in an external Application.

Without any explanation I consider this a major annoyance, especially as it does not even tell me what kind of application it wants to open. It just tries to delegate to `xdg-open` to find the actual handler of the link type.

**Comment by alexdovzhanyn** [comment]
Ah that sounds like what telegram does. The link to the home page is
currently a link to our telegram group where we're having all discussion
around development at the moment -- we don't yet have a website.

Once the language matures a bit and we have some spare time to dedicate
towards putting together a website, that'll be resolved.

In the meantime it might make sense to replace that with a GitHub pages
link
